// File generated by FlutterFire CLI.
// Regenerate with: flutterfire configure --project=astro-phase-2
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'FCM is configured for Android and iOS only on this app.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLoFQiB63oBl8MEfZhB5LcQVvggSQEUUY',
    appId: '1:989465603805:android:08810295d95e238f84b534',
    messagingSenderId: '989465603805',
    projectId: 'astro-phase-2',
    storageBucket: 'astro-phase-2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1iA9F4XCvUgiCXAYtVJKHHTCn0of24KA',
    appId: '1:989465603805:ios:1c0956fb7cb2e97384b534',
    messagingSenderId: '989465603805',
    projectId: 'astro-phase-2',
    storageBucket: 'astro-phase-2.firebasestorage.app',
    iosBundleId: 'com.rudraganga.rgUser',
  );
}
